---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.0.0
    hooks:
      - id: tofu_fmt
        args: ["--args=-recursive"]  # , "--args=-check"]
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.19.0
    hooks:
      - id: terraform-docs-go
        name: tfdocs - network module
        args: ["network"]
