# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.0.0
    hooks:
      - id: tofu_fmt
#      - id: tofu_docs

#  - repo: https://github.com/terraform-docs/terraform-docs
#    rev: v0.16.0
#    hooks:
#      - id: terraform-docs-network
#        name: tfdocs - network
#        args: ["markdown", "table", "--output-file", "README.md", "network"]
#  - repo: https://github.com/gruntwork-io/pre-commit
#    rev: v0.1.23
#    hooks:
#      - id: terraform-fmt
#        args: ["-check"]
